version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: quantera-postgres
    environment:
      POSTGRES_PASSWORD: quantera_dev
      POSTGRES_DB: quantera_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
    container_name: quantera-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  ipfs:
    image: ipfs/kubo:latest
    container_name: quantera-ipfs
    ports:
      - "5001:5001"  # API
      - "8080:8080"  # Gateway
      - "4001:4001"  # Swarm
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_export:/export
    environment:
      - IPFS_PROFILE=server

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  ipfs_data:
    driver: local
  ipfs_export:
    driver: local
