name = "quantera-platform"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "frontend/build"
entry-point = "workers-site"

[build]
command = "cd frontend && npm install --legacy-peer-deps && CI=false npm run build"
upload.format = "service-worker"

[build.upload]
format = "service-worker" 