name: Bug Report
description: Report a bug or unexpected behavior in Quantera
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out this form as completely as possible.

        **Note**: For security vulnerabilities, please follow our [Security Policy](https://github.com/Carbon-Twelve-C12/quantera/security/policy) instead of opening a public issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the behavior.
      placeholder: |
        1. Navigate to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Platform unusable, data loss, security issue
        - High - Major feature broken, no workaround
        - Medium - Feature impaired, workaround available
        - Low - Minor inconvenience, cosmetic issue
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the platform is affected?
      multiple: true
      options:
        - Marketplace
        - Portfolio
        - Wallet Connection
        - Asset Creation
        - Yield Strategies
        - Liquidity Pools
        - Smart Accounts
        - Trade Finance
        - Environmental Assets
        - Analytics/Dashboard
        - Authentication
        - API
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: e.g., Chrome 120, Firefox 121, Safari 17
    validations:
      required: false

  - type: input
    id: wallet
    attributes:
      label: Wallet
      description: Which wallet were you using (if applicable)?
      placeholder: e.g., MetaMask, WalletConnect, Coinbase Wallet
    validations:
      required: false

  - type: input
    id: network
    attributes:
      label: Network
      description: Which blockchain network (if applicable)?
      placeholder: e.g., Ethereum Mainnet, Sepolia, Polygon
    validations:
      required: false

  - type: textarea
    id: console
    attributes:
      label: Console Errors
      description: Any errors from the browser console (F12 > Console tab)?
      placeholder: Paste console errors here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem.
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem?
      placeholder: Add any other information here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have provided all the information needed to reproduce this bug
          required: true
        - label: This is not a security vulnerability (those should be reported privately)
          required: true
