name: Feature Request
description: Suggest a new feature or enhancement for Quantera
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is there a frustration or gap you're experiencing?
      placeholder: |
        I'm always frustrated when...
        Currently, there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented.
      placeholder: |
        I would like to be able to...
        The feature should work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives or workarounds have you considered?
      placeholder: Describe any alternative solutions or features you've considered...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the platform does this feature relate to?
      options:
        - Marketplace & Trading
        - Portfolio Management
        - Yield Strategies
        - Liquidity Pools
        - Smart Accounts
        - Asset Creation
        - Environmental/ESG
        - Analytics & Reporting
        - Wallet & Authentication
        - API & Integrations
        - Mobile Experience
        - Performance
        - Accessibility
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have - Would improve experience
        - Important - Significantly impacts workflow
        - Critical - Cannot effectively use platform without it
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: What type of user would benefit from this feature?
      multiple: true
      options:
        - Retail Investor
        - Institutional Investor
        - Asset Issuer
        - Developer/Integrator
        - Administrator
        - All Users
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add mockups, wireframes, or examples from other platforms.
      placeholder: Drag and drop images here or describe visual concepts...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, use cases, or information about the feature request?
      placeholder: Add any other context here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature aligns with Quantera's mission as an asset tokenization platform
          required: true
